language: node_js
node_js:
  - "8"
branches:
  only:
    - develop
cache: yarn

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.16.0
  - export PATH="$HOME/.yarn/bin:$PATH"
  - export VUE_BRANCHES="gh-pages"

install:
  - yarn install
  - yarn build

script:
  echo "test"

deploy:
  condition: env(GITHUB_TOKEN) IS present
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  repo: whitewoodcity/social-vertex-website
  target-branch: gh-pages
  local-dir: ./dist
  on:
    branch: develop
